### ISSUE TITLE
Grounded-SAM-2/grounded_sam2_hf_model_demo.py doesn't work with transformers v 4.55.0 and later

### ISSUE THREAD

**Issue by rdm12** [IDEA-Research/Grounded-SAM-2#116]
- `transformers` v 4.55.0 and later:
```
python3 grounded_sam2_hf_model_demo.py 

Traceback (most recent call last):
  File "grounded_sam2_hf_model_demo.py", line 111, in <module>
    results = processor.post_process_grounded_object_detection(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GroundingDinoProcessor.post_process_grounded_object_detection() got an unexpected keyword argument 'box_threshold'  
```
- `transformers` v 4.54.0 and earlier works fine

**Comment by paruparu** [comment]
In recent releases of transformers, the GroundingDinoProcessor API has been refactored.
The post_process_grounded_object_detection() method no longer accepts the argument box_threshold.
Instead, it now expects:

`threshold=<float>         # replaces box_threshold`

At least worked with my version 4.57.1
